version: "2"
services:
  front:
    # env_file: "./Front-end/.env"
    image: marcpartensky/shelp-front
    build: front
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - back
  back:
    image: marcpartensky/shelp-back
    env_file: "./back/.env"
    build: back
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
